name: “Now Now” for Git Things Done
description: '…'
inputs:
  token:
    description: Usually `secrets.GITHUB_TOKEN`
    default: ${{ github.token }}
    required: true
  yesterday:
    description: >
      Yesterday’s entry issue number.
      If unset we use `$GTD_YESTERDAY`.
    required: false
  today:
    description: >
      Today’s entry issue number.
      If unset we use `$GTD_TODAY`.
    required: false
runs:
  using: docker
  image: Dockerfile
  # ^^ because we want node 16 so we can use modern features
