name: “Now Now” for Git Things Done
description: '…'
inputs:
  token:
    description: Usually `secrets.GITHUB_TOKEN`
    default: ${{ github.token }}
    required: true
  yesterday:
    description: >
      Yesterday’s entry issue number.
      If unset we use `$GTD_YESTERDAY`.
    required: false
  today:
    description: >
      Today’s entry issue number.
      If unset we use `$GTD_TODAY`.
    required: false
  name:
    description: >
      Look for a comment with this title.
      eg. `foo` will look for a comment that *begins* with `# foo`.
      Defaults to a comment titled “Now Now” or “Right Now”.
    required: false
runs:
  using: node16
  main: dist/index.js

branding:
  icon: check-square
  color: green
